name: test

on: [push]

jobs:
  test:
    container: circleci/node:16-browsers
    runs-on: ubuntu-18.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CI_BOT_URL }}
      JOBS: 1
      NODE_OPTIONS: "--max_old_space_size=4096"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - name: npm lint
        run: |
          npm run lint:js
      - name: npm test
        run: |
          npm run test -- -r=dot
